using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Linq;
using cAlgo.API;
using cAlgo.API.Collections;
using cAlgo.API.Indicators;
using cAlgo.API.Internals;

namespace cAlgo
{
    public enum SystemColor
    {
        Transparent,
        AliceBlue,
        AntiqueWhite,
        Aqua,
        Aquamarine,
        Azure,
        Beige,
        Bisque,
        Black,
        BlanchedAlmond,
        Blue,
        BlueViolet,
        Brown,
        BurlyWood,
        CadetBlue,
        Chartreuse,
        Chocolate,
        Coral,
        CornflowerBlue,
        Cornsilk,
        Crimson,
        Cyan,
        DarkBlue,
        DarkCyan,
        DarkGoldenrod,
        DarkGray,
        DarkGreen,
        DarkKhaki,
        DarkMagenta,
        DarkOliveGreen,
        DarkOrange,
        DarkOrchid,
        DarkRed,
        DarkSalmon,
        DarkSeaGreen,
        DarkSlateBlue,
        DarkSlateGray,
        DarkTurquoise,
        DarkViolet,
        DeepPink,
        DeepSkyBlue,
        DimGray,
        DodgerBlue,
        Firebrick,
        FloralWhite,
        ForestGreen,
        Fuchsia,
        Gainsboro,
        GhostWhite,
        Gold,
        Goldenrod,
        Gray,
        Green,
        GreenYellow,
        Honeydew,
        HotPink,
        IndianRed,
        Indigo,
        Ivory,
        Khaki,
        Lavender,
        LavenderBlush,
        LawnGreen,
        LemonChiffon,
        LightBlue,
        LightCoral,
        LightCyan,
        LightGoldenrodYellow,
        LightGray,
        LightGreen,
        LightPink,
        LightSalmon,
        LightSeaGreen,
        LightSkyBlue,
        LightSlateGray,
        LightSteelBlue,
        LightYellow,
        Lime,
        LimeGreen,
        Linen,
        Magenta,
        Maroon,
        MediumAquamarine,
        MediumBlue,
        MediumOrchid,
        MediumPurple,
        MediumSeaGreen,
        MediumSlateBlue,
        MediumSpringGreen,
        MediumTurquoise,
        MediumVioletRed,
        MidnightBlue,
        MintCream,
        MistyRose,
        Moccasin,
        NavajoWhite,
        Navy,
        OldLace,
        Olive,
        OliveDrab,
        Orange,
        OrangeRed,
        Orchid,
        PaleGoldenrod,
        PaleGreen,
        PaleTurquoise,
        PaleVioletRed,
        PapayaWhip,
        PeachPuff,
        Peru,
        Pink,
        Plum,
        PowderBlue,
        Purple,
        Red,
        RosyBrown,
        RoyalBlue,
        SaddleBrown,
        Salmon,
        SandyBrown,
        SeaGreen,
        SeaShell,
        Sienna,
        Silver,
        SkyBlue,
        SlateBlue,
        SlateGray,
        Snow,
        SpringGreen,
        SteelBlue,
        Tan,
        Teal,
        Thistle,
        Tomato,
        Turquoise,
        Violet,
        Wheat,
        White,
        WhiteSmoke,
        Yellow,
        YellowGreen
    }


    public static class CTraderFunctions
    {
        static Dictionary<SystemColor, Color> colorMap = new Dictionary<SystemColor, Color>()
            {
                {SystemColor.Transparent, Color.Transparent},
                {SystemColor.AliceBlue, Color.AliceBlue},
                {SystemColor.AntiqueWhite, Color.AntiqueWhite},
                {SystemColor.Aqua, Color.Aqua},
                {SystemColor.Aquamarine, Color.Aquamarine},
                {SystemColor.Azure, Color.Azure},
                {SystemColor.Beige, Color.Beige},
                {SystemColor.Bisque, Color.Bisque},
                {SystemColor.Black, Color.Black},
                {SystemColor.BlanchedAlmond, Color.BlanchedAlmond},
                {SystemColor.Blue, Color.Blue},
                {SystemColor.BlueViolet, Color.BlueViolet},
                {SystemColor.Brown, Color.Brown},
                {SystemColor.BurlyWood, Color.BurlyWood},
                {SystemColor.CadetBlue, Color.CadetBlue},
                {SystemColor.Chartreuse, Color.Chartreuse},
                {SystemColor.Chocolate, Color.Chocolate},
                {SystemColor.Coral, Color.Coral},
                {SystemColor.CornflowerBlue, Color.CornflowerBlue},
                {SystemColor.Cornsilk, Color.Cornsilk},
                {SystemColor.Crimson, Color.Crimson},
                {SystemColor.Cyan, Color.Cyan},
                {SystemColor.DarkBlue, Color.DarkBlue},
                {SystemColor.DarkCyan, Color.DarkCyan},
                {SystemColor.DarkGoldenrod, Color.DarkGoldenrod},
                {SystemColor.DarkGray, Color.DarkGray},
                {SystemColor.DarkGreen, Color.DarkGreen},
                {SystemColor.DarkKhaki, Color.DarkKhaki},
                {SystemColor.DarkMagenta, Color.DarkMagenta},
                {SystemColor.DarkOliveGreen, Color.DarkOliveGreen},
                {SystemColor.DarkOrange, Color.DarkOrange},
                {SystemColor.DarkOrchid, Color.DarkOrchid},
                {SystemColor.DarkRed, Color.DarkRed},
                {SystemColor.DarkSalmon, Color.DarkSalmon},
                {SystemColor.DarkSeaGreen, Color.DarkSeaGreen},
                {SystemColor.DarkSlateBlue, Color.DarkSlateBlue},
                {SystemColor.DarkSlateGray, Color.DarkSlateGray},
                {SystemColor.DarkTurquoise, Color.DarkTurquoise},
                {SystemColor.DarkViolet, Color.DarkViolet},
                {SystemColor.DeepPink, Color.DeepPink},
                {SystemColor.DeepSkyBlue, Color.DeepSkyBlue},
                {SystemColor.DimGray, Color.DimGray},
                {SystemColor.DodgerBlue, Color.DodgerBlue},
                {SystemColor.Firebrick, Color.Firebrick},
                {SystemColor.FloralWhite, Color.FloralWhite},
                {SystemColor.ForestGreen, Color.ForestGreen},
                {SystemColor.Fuchsia, Color.Fuchsia},
                {SystemColor.Gainsboro, Color.Gainsboro},
                {SystemColor.GhostWhite, Color.GhostWhite},
                {SystemColor.Gold, Color.Gold},
                {SystemColor.Goldenrod, Color.Goldenrod},
                {SystemColor.Gray, Color.Gray},
                {SystemColor.Green, Color.Green},
                {SystemColor.GreenYellow, Color.GreenYellow},
                {SystemColor.Honeydew, Color.Honeydew},
                {SystemColor.HotPink, Color.HotPink},
                {SystemColor.IndianRed, Color.IndianRed},
                {SystemColor.Indigo, Color.Indigo},
                {SystemColor.Ivory, Color.Ivory},
                {SystemColor.Khaki, Color.Khaki},
                {SystemColor.Lavender, Color.Lavender},
                {SystemColor.LavenderBlush, Color.LavenderBlush},
                {SystemColor.LawnGreen, Color.LawnGreen},
                {SystemColor.LemonChiffon, Color.LemonChiffon},
                {SystemColor.LightBlue, Color.LightBlue},
                {SystemColor.LightCoral, Color.LightCoral},
                {SystemColor.LightCyan, Color.LightCyan},
                {SystemColor.LightGoldenrodYellow, Color.LightGoldenrodYellow},
                {SystemColor.LightGray, Color.LightGray},
                {SystemColor.LightGreen, Color.LightGreen},
                {SystemColor.LightPink, Color.LightPink},
                {SystemColor.LightSalmon, Color.LightSalmon},
                {SystemColor.LightSeaGreen, Color.LightSeaGreen},
                {SystemColor.LightSkyBlue, Color.LightSkyBlue},
                {SystemColor.LightSlateGray, Color.LightSlateGray},
                {SystemColor.LightSteelBlue, Color.LightSteelBlue},
                {SystemColor.LightYellow, Color.LightYellow},
                {SystemColor.Lime, Color.Lime},
                {SystemColor.LimeGreen, Color.LimeGreen},
                {SystemColor.Linen, Color.Linen},
                {SystemColor.Magenta, Color.Magenta},
                {SystemColor.Maroon, Color.Maroon},
                {SystemColor.MediumAquamarine, Color.MediumAquamarine},
                {SystemColor.MediumBlue, Color.MediumBlue},
                {SystemColor.MediumOrchid, Color.MediumOrchid},
                {SystemColor.MediumPurple, Color.MediumPurple},
                {SystemColor.MediumSeaGreen, Color.MediumSeaGreen},
                {SystemColor.MediumSlateBlue, Color.MediumSlateBlue},
                {SystemColor.MediumSpringGreen, Color.MediumSpringGreen},
                {SystemColor.MediumTurquoise, Color.MediumTurquoise},
                {SystemColor.MediumVioletRed, Color.MediumVioletRed},
                {SystemColor.MidnightBlue, Color.MidnightBlue},
                {SystemColor.MintCream, Color.MintCream},
                {SystemColor.MistyRose, Color.MistyRose},
                {SystemColor.Moccasin, Color.Moccasin},
                {SystemColor.NavajoWhite, Color.NavajoWhite},
                {SystemColor.Navy, Color.Navy},
                {SystemColor.OldLace, Color.OldLace},
                {SystemColor.Olive, Color.Olive},
                {SystemColor.OliveDrab, Color.OliveDrab},
                {SystemColor.Orange, Color.Orange},
                {SystemColor.OrangeRed, Color.OrangeRed},
                {SystemColor.Orchid, Color.Orchid},
                {SystemColor.PaleGoldenrod, Color.PaleGoldenrod},
                {SystemColor.PaleGreen, Color.PaleGreen},
                {SystemColor.PaleTurquoise, Color.PaleTurquoise},
                {SystemColor.PaleVioletRed, Color.PaleVioletRed},
                {SystemColor.PapayaWhip, Color.PapayaWhip},
                {SystemColor.PeachPuff, Color.PeachPuff},
                {SystemColor.Peru, Color.Peru},
                {SystemColor.Pink, Color.Pink},
                {SystemColor.Plum, Color.Plum},
                {SystemColor.PowderBlue, Color.PowderBlue},
                {SystemColor.Purple, Color.Purple},
                {SystemColor.Red, Color.Red},
                {SystemColor.RosyBrown, Color.RosyBrown},
                {SystemColor.RoyalBlue, Color.RoyalBlue},
                {SystemColor.SaddleBrown, Color.SaddleBrown},
                {SystemColor.Salmon, Color.Salmon},
                {SystemColor.SandyBrown, Color.SandyBrown},
                {SystemColor.SeaGreen, Color.SeaGreen},
                {SystemColor.SeaShell, Color.SeaShell},
                {SystemColor.Sienna, Color.Sienna},
                {SystemColor.Silver, Color.Silver},
                {SystemColor.SkyBlue, Color.SkyBlue},
                {SystemColor.SlateBlue, Color.SlateBlue},
                {SystemColor.SlateGray, Color.SlateGray},
                {SystemColor.Snow, Color.Snow},
                {SystemColor.SpringGreen, Color.SpringGreen},
                {SystemColor.SteelBlue, Color.SteelBlue},
                {SystemColor.Tan, Color.Tan},
                {SystemColor.Teal, Color.Teal},
                {SystemColor.Thistle, Color.Thistle},
                {SystemColor.Tomato, Color.Tomato},
                {SystemColor.Turquoise, Color.Turquoise},
                {SystemColor.Violet, Color.Violet},
                {SystemColor.Wheat, Color.Wheat},
                {SystemColor.White, Color.White},
                {SystemColor.WhiteSmoke, Color.WhiteSmoke},
                {SystemColor.Yellow, Color.Yellow},
                {SystemColor.YellowGreen, Color.YellowGreen}
            };

        public static Color ToCtraderColor(this SystemColor color)
        {
            return colorMap[color];
        }
    }
}
