using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using cAlgo.API;
using cAlgo.API.Collections;
using cAlgo.API.Indicators;
using cAlgo.API.Internals;

namespace cAlgo
{
    internal class TimeframeTranslator
    {
        static Dictionary<string, TimeFrame> timeframeMap = new Dictionary<string, TimeFrame> {
            {"t1", TimeFrame.Tick},
            {"t2", TimeFrame.Tick2},
            { "t3", TimeFrame.Tick3},
            { "t4", TimeFrame.Tick4},
            { "t5", TimeFrame.Tick5},
            { "t6", TimeFrame.Tick6},
            { "t7", TimeFrame.Tick7},
            { "t9", TimeFrame.Tick9},
            { "t10", TimeFrame.Tick10},
            { "t15", TimeFrame.Tick15},
            { "t20", TimeFrame.Tick20},
            { "t25", TimeFrame.Tick25},
            { "t30", TimeFrame.Tick30},
            { "t40", TimeFrame.Tick40},
            { "t50", TimeFrame.Tick50},
            { "t60", TimeFrame.Tick60},
            { "t80", TimeFrame.Tick80},
            { "t90", TimeFrame.Tick90},
            { "t100", TimeFrame.Tick100},
            { "t150", TimeFrame.Tick150},
            { "t200", TimeFrame.Tick200},
            { "t250", TimeFrame.Tick250},
            { "t300", TimeFrame.Tick300},
            { "t500", TimeFrame.Tick500},
            { "t750", TimeFrame.Tick750},
            { "t1000", TimeFrame.Tick1000},
            { "m1", TimeFrame.Minute},
            { "m2", TimeFrame.Minute2},
            { "m3", TimeFrame.Minute3},
            { "m4", TimeFrame.Minute4},
            { "m5", TimeFrame.Minute5},
            { "m6", TimeFrame.Minute6},
            { "m7", TimeFrame.Minute7},
            { "m8", TimeFrame.Minute8},
            { "m9", TimeFrame.Minute9},
            { "m10", TimeFrame.Minute10},
            { "m15", TimeFrame.Minute15},
            { "m20", TimeFrame.Minute20},
            { "m30", TimeFrame.Minute30},
            { "m45", TimeFrame.Minute45},
            { "h1", TimeFrame.Hour},
            { "h2", TimeFrame.Hour2},
            { "h3", TimeFrame.Hour3},
            { "h4", TimeFrame.Hour4},
            { "h6", TimeFrame.Hour6},
            { "h8", TimeFrame.Hour8},
            { "h12", TimeFrame.Hour12},
            { "D1", TimeFrame.Daily},
            { "D2", TimeFrame.Day2},
            { "D3", TimeFrame.Day3},
            { "W1", TimeFrame.Weekly},
            { "Month1", TimeFrame.Monthly},
            { "Re1", TimeFrame.Renko1},
            { "Re2", TimeFrame.Renko2},
            { "Re3", TimeFrame.Renko3},
            { "Re4", TimeFrame.Renko4},
            { "Re5", TimeFrame.Renko5},
            { "Re6", TimeFrame.Renko6},
            { "Re7", TimeFrame.Renko7},
            { "Re8", TimeFrame.Renko8},
            { "Re9", TimeFrame.Renko9},
            { "Re10", TimeFrame.Renko10},
            { "Re15", TimeFrame.Renko15},
            { "Re20", TimeFrame.Renko20},
            { "Re25", TimeFrame.Renko25},
            { "Re30", TimeFrame.Renko30},
            { "Re35", TimeFrame.Renko35},
            { "Re40", TimeFrame.Renko40},
            { "Re45", TimeFrame.Renko45},
            { "Re50", TimeFrame.Renko50},
            { "Re100", TimeFrame.Renko100},
            { "Re150", TimeFrame.Renko150},
            { "Re200", TimeFrame.Renko200},
            { "Re300", TimeFrame.Renko300},
            { "Re500", TimeFrame.Renko500},
            { "Re800", TimeFrame.Renko800},
            { "Re1000", TimeFrame.Renko1000},
            { "Re2000", TimeFrame.Renko2000},
            { "Ra1", TimeFrame.Range1},
            { "Ra2", TimeFrame.Range2},
            { "Ra3", TimeFrame.Range3},
            { "Ra4", TimeFrame.Range4},
            { "Ra5", TimeFrame.Range5},
            { "Ra8", TimeFrame.Range8},
            { "Ra10", TimeFrame.Range10},
            { "Ra20", TimeFrame.Range20},
            { "Ra30", TimeFrame.Range30},
            { "Ra50", TimeFrame.Range50},
            { "Ra80", TimeFrame.Range80},
            { "Ra100", TimeFrame.Range100},
            { "Ra150", TimeFrame.Range150},
            { "Ra200", TimeFrame.Range200},
            { "Ra300", TimeFrame.Range300},
            { "Ra500", TimeFrame.Range500},
            { "Ra800", TimeFrame.Range800},
            { "Ra1000", TimeFrame.Range1000},
            { "Ra2000", TimeFrame.Range2000},
            { "Ra5000", TimeFrame.Range5000},
            { "Ra7500", TimeFrame.Range7500},
            { "Ra10000", TimeFrame.Range10000},
            { "Hm1", TimeFrame.HeikinMinute},
            { "Hm2", TimeFrame.HeikinMinute2},
            { "Hm3", TimeFrame.HeikinMinute3},
            { "Hm4", TimeFrame.HeikinMinute4},
            { "Hm5", TimeFrame.HeikinMinute5},
            { "Hm6", TimeFrame.HeikinMinute6},
            { "Hm7", TimeFrame.HeikinMinute7},
            { "Hm8", TimeFrame.HeikinMinute8},
            { "Hm9", TimeFrame.HeikinMinute9},
            { "Hm10", TimeFrame.HeikinMinute10},
            { "Hm15", TimeFrame.HeikinMinute15},
            { "Hm20", TimeFrame.HeikinMinute20},
            { "Hm30", TimeFrame.HeikinMinute30},
            { "Hm45", TimeFrame.HeikinMinute45},
            { "Hh1", TimeFrame.HeikinHour},
            { "Hh2", TimeFrame.HeikinHour2},
            { "Hh3", TimeFrame.HeikinHour3},
            { "Hh4", TimeFrame.HeikinHour4},
            { "Hh6", TimeFrame.HeikinHour6},
            { "Hh8", TimeFrame.HeikinHour8},
            { "Hh12", TimeFrame.HeikinHour12},
            { "HD1", TimeFrame.HeikinDaily},
            { "HD2", TimeFrame.HeikinDay2},
            { "HD3", TimeFrame.HeikinDay3},
            { "HW1", TimeFrame.HeikinWeekly},
            { "HMonth1", TimeFrame.HeikinMonthly},
        };

        public static TimeFrame translate(String value)
        {
            return timeframeMap[value];
        }
    }
}
